/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.awt.CardLayout;
import model.Feature;
import model.Product;
import model.ProductCatalog;
import model.Supplier;
import model.SupplierDirectory;

/**
 *
 * @author archil
 */
public class MainJFrame extends javax.swing.JFrame {

    SupplierDirectory supplierDirectory;
    
    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() {
        initComponents(); //set up the GUI
        
        this.supplierDirectory = new SupplierDirectory();
        setSize(800,600);
        setResizable(false);
       
        //populate sample data
        populateSampleData();
        
        setLoginScreen();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainWorkArea = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainWorkArea.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainWorkArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainWorkArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    private void setLoginScreen() {
        LoginScreen loginScreen = new LoginScreen(mainWorkArea, supplierDirectory);
        mainWorkArea.add("LoginScreen", loginScreen);
        CardLayout layout = (CardLayout) mainWorkArea.getLayout();
        layout.next(mainWorkArea);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel mainWorkArea;
    // End of variables declaration//GEN-END:variables

    private void populateSampleData() {
        // create suppliers and get productCatalog
        Supplier s1= supplierDirectory.addSupplier();
        s1.setSupplyName("McDonald's");
        ProductCatalog productCatalog1 = s1.getProductCatalog();
        
        Supplier s2= supplierDirectory.addSupplier();
        s2.setSupplyName("Popeyes");
        ProductCatalog productCatalog2 = s2.getProductCatalog();
        
        Supplier s3= supplierDirectory.addSupplier();
        s3.setSupplyName("Dunkin'");
        ProductCatalog productCatalog3 = s3.getProductCatalog();
        
        // create product and add to product catalog
        Product p1 = productCatalog1.addProduct();
        p1.setName("Big Mac");
        p1.setPrice(6);        
        
        Product p2 = productCatalog1.addProduct();
        p2.setName("Fries");
        p2.setPrice(4);
        
        Product p3 = productCatalog2.addProduct();
        p3.setName("Wings");
        p3.setPrice(7);
        
        Product p4 = productCatalog2.addProduct();
        p4.setName("Tenders");
        p4.setPrice(10);
        
        Product p5 = productCatalog3.addProduct();
        p5.setName("Glazed Donut");
        p5.setPrice(2);
        
        Product p6 = productCatalog3.addProduct();
        p6.setName("Hot Coffee");
        p6.setPrice(3);
        
        // add features
        Feature f1 = p1.addFeature();
        f1.setName("Calories");
        f1.setValue("590");
        
        Feature f2 = p2.addFeature();
        f2.setName("Calories");
        f2.setValue("320");
        
        Feature f3 = p2.addFeature();
        f3.setName("Condiment");
        f3.setValue("Ketchup");
        
        Feature f4 = p3.addFeature();
        f4.setName("Pieces");
        f4.setValue("6");
        
        Feature f5 = p4.addFeature();
        f5.setName("Pieces");
        f5.setValue("3");
        
        Feature f6 = p5.addFeature();
        f6.setName("Calories");
        f6.setValue("240");
        
        Feature f7 = p6.addFeature();
        f7.setName("Size");
        f7.setValue("Medium");
    }

    
}
